### ISSUE TITLE
想试下 taro 发现跑不起来

### ISSUE THREAD

**Issue by viewweiwu** [wangcheng/connect-miniprogram#10]
有个依赖是 `"@buf/connectrpc_eliza.connectrpc_es": "^1.1.3-20230913231627-233fca715f49.1"` ，这个是在私有仓库吗？

**Comment by wangcheng** [comment]
是的，我好像忘了写清楚了。这个文档里有写怎么添加私有仓库 https://connectrpc.com/docs/web/getting-started#generating-the-client
