### ISSUE TITLE
大佬你好，编译成小红书小程序，貌似无法运行，一直报错

### ISSUE THREAD

**Issue by xixihhhh** [wangcheng/connect-miniprogram#18]
![screenshot-20241123-180353](https://github.com/user-attachments/assets/d406ca09-d796-4740-a534-99ae263caf52)
引入了headers polyfill就一直报错

**Comment by wangcheng** [comment]
不好意思，我只在微信上测试过 😂 抽时间我看一下小红书吧。

**Comment by wangcheng** [comment]
https://github.com/wangcheng/connect-miniprogram/tree/xhs/packages/example-xhs
我写了一小红书的最简单的例子，试了一下没问题。你能不能发一下你的具体情况？比如用的什么框架，什么配置？
